services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    environment:
      - PROFILE_ACTIVES=prd
      - ENDPOINT=${ENDPOINT:http://10.1.11.179:9008}
      - ACCESS_KEY=${ACCESS_KEY:miniouser}
      - SECRET-KEY=${SECRET-KEY:miniopassword}
      - BUCKET_NAME=${BUCKET_NAME:fee-charge-bucket}
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - uploads-service
    volumes:
      - logs:/logs/app/logs
      - uploads:/uploads/app/uploads

volumes:
    logs:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /data/logs/uploads-service/logs
    uploads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /data/logs/uploads-service/uploads

networks:
  app-network:
    driver: bridge
